/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSubscriptionsRouteImport } from './routes/dashboard/subscriptions'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardGroupsRouteImport } from './routes/dashboard/groups'
import { Route as DashboardExpensesRouteImport } from './routes/dashboard/expenses'
import { Route as AuthSuccessRouteImport } from './routes/auth/success'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubscriptionsRoute = DashboardSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGroupsRoute = DashboardGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExpensesRoute = DashboardExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSuccessRoute = AuthSuccessRouteImport.update({
  id: '/auth/success',
  path: '/auth/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/success': typeof AuthSuccessRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/groups': typeof DashboardGroupsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/success': typeof AuthSuccessRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/groups': typeof DashboardGroupsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/success': typeof AuthSuccessRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/groups': typeof DashboardGroupsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/success'
    | '/dashboard/expenses'
    | '/dashboard/groups'
    | '/dashboard/settings'
    | '/dashboard/subscriptions'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/success'
    | '/dashboard/expenses'
    | '/dashboard/groups'
    | '/dashboard/settings'
    | '/dashboard/subscriptions'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/success'
    | '/dashboard/expenses'
    | '/dashboard/groups'
    | '/dashboard/settings'
    | '/dashboard/subscriptions'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthSuccessRoute: typeof AuthSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/subscriptions': {
      id: '/dashboard/subscriptions'
      path: '/subscriptions'
      fullPath: '/dashboard/subscriptions'
      preLoaderRoute: typeof DashboardSubscriptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/groups': {
      id: '/dashboard/groups'
      path: '/groups'
      fullPath: '/dashboard/groups'
      preLoaderRoute: typeof DashboardGroupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/expenses': {
      id: '/dashboard/expenses'
      path: '/expenses'
      fullPath: '/dashboard/expenses'
      preLoaderRoute: typeof DashboardExpensesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/success': {
      id: '/auth/success'
      path: '/auth/success'
      fullPath: '/auth/success'
      preLoaderRoute: typeof AuthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardExpensesRoute: typeof DashboardExpensesRoute
  DashboardGroupsRoute: typeof DashboardGroupsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSubscriptionsRoute: typeof DashboardSubscriptionsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardExpensesRoute: DashboardExpensesRoute,
  DashboardGroupsRoute: DashboardGroupsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSubscriptionsRoute: DashboardSubscriptionsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthSuccessRoute: AuthSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
